name: "#22"
on: [push, pull_request]
jobs:
  instrumentationJob:
    name: Run Instrumentation Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: malinskiy/action-android/install-sdk@release/0.0.6
      - run: adb devices
      - run: echo $ANDROID_HOME
      - uses: malinskiy/action-android/emulator-run-cmd@release/0.0.6
        with:
          cmd: ./gradlew connectedDebugAndroidTest
          api: 25
          tag: default
          abi: x86
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log
